const internetSpeed = [
  "Monaco",
  "Singapore",
  "Hong Kong",
  "Romania",
  "Switzerland",
  "Denmark",
  "Thailand",
  "Chile",
  "France",
  "South Korea",
  "Hungary",
  "Liechtenstein",
  "United States",
  "Spain",
  "China",
  "United Arab Emirates",
  "Canada",
  "Macau",
  "Japan",
  "Sweden",
  "Luxembourg",
  "Andorra",
  "New Zealand",
  "Norway",
  "Netherlands",
  "Israel",
  "Portugal",
  "Poland",
  "Moldova",
  "Taiwan",
  "Kuwait",
  "Lithuania",
  "Malta",
  "Panama",
  "Germany",
  "Latvia",
  "Finland",
  "Belgium",
  "Ireland",
  "San Marino",
  "Slovenia",
  "Slovakia",
  "Qatar",
  "Brazil",
  "Barbados",
  "Malaysia",
  "Italy",
  "United Kingdom",
  "Russia",
  "Saudi Arabia",
  "Austria",
  "Estonia",
  "Serbia",
  "Bulgaria",
  "Trinidad and Tobago",
  "Jordan",
  "Australia",
  "Vietnam",
  "Ukraine",
  "Bahrain",
  "Paraguay",
  "Colombia",
  "Philippines",
  "Uruguay",
  "Belarus",
  "Croatia",
  "Oman",
  "Guyana",
  "India",
  "Kazakhstan",
  "Bahamas",
  "Montenegro",
  "Argentina",
  "Peru",
  "Grenada",
  "Costa Rica",
  "Cyprus",
  "Mexico",
  "South Africa",
  "Saint Vincent and the Grenadines",
  "Mongolia",
  "Saint Lucia",
  "Ghana",
  "Kyrgyzstan",
  "Bosnia and Herzegovina",
  "Laos",
  "Uzbekistan",
  "Albania",
  "Turkey",
  "North Macedonia",
  "Madagascar",
  "Ivory Coast",
  "Belize",
  "Bangladesh",
  "Egypt",
  "Mauritius",
  "Greece",
  "Ecuador",
  "Armenia",
  "Jamaica",
  "Tajikistan",
  "Saint Kitts and Nevis",
  "Senegal",
  "Dominica",
  "Brunei",
  "Nepal",
  "Dominican Republic",
  "Iraq",
  "Marshall Islands",
  "Nicaragua",
  "Palestine",
  "Georgia",
  "Cambodia",
  "Indonesia",
  "Bolivia",
  "Maldives",
  "Morocco",
  "El Salvador",
  "Cape Verde",
  "Honduras",
  "Rwanda",
  "Sri Lanka",
  "Liberia",
  "Burkina Faso",
  "Azerbaijan",
  "Seychelles",
  "Bhutan",
  "Lesotho",
  "Venezuela",
  "Guatemala",
  "Western Sahara",
  "Micronesia",
  "Gabon",
  "Iran",
  "Antigua and Barbuda",
  "Mali",
  "Togo",
  "Fiji",
  "Myanmar",
  "Haiti",
  "Tanzania",
  "Namibia",
  "Kenya",
  "Somalia",
  "Djibouti",
  "Lebanon",
  "Zimbabwe",
  "Nigeria",
  "Zambia",
  "Benin",
  "Vanuatu",
  "Libya",
  "Suriname",
  "Angola",
  "Ethiopia",
  "Cameroon",
  "Pakistan",
  "Papua New Guinea",
  "Sierra Leone",
  "Uganda",
  "Syria",
  "Malawi",
  "Gambia",
  "Niger",
  "Mauritania",
  "Botswana",
  "Burundi",
  "Tunisia",
  "Algeria",
  "Mozambique",
  "Guinea",
  "Afghanistan",
  "Equatorial Guinea",
  "Sudan",
  "Yemen",
  "Turkmenistan",
  "Cuba",
];
